version: 2
jobs:
  build:
    working_directory: ~/circleci
    docker:
      - image: circleci/python:3.7.0-browsers
      - image: circleci/postgres:10-postgis
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: circleci
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            poetry config settings.virtualenvs.create false
            poetry install
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Check formatting
          command: |
            . venv/bin/activate
            make lint
      - run:
          command: |
            . venv/bin/activate
            make test
      - store_artifacts:
          path: test-reports/
          destination: tr1

workflows:
  version: 2
  build-then-deploy:
    jobs:
      - build
